<a href="https://colab.research.google.com/github/chaiminwoo0223/Machine-Learning/blob/main/11_Ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol','sugar','pH']].to_numpy()
target = wine['class'].to_numpy()
train_input, test_input, train_target, test_target = train_test_split(
    data,target,test_size=0.2,random_state=42)

In [2]:
# 랜덤 포레스트(부트스트랩 사용 ㅇ)
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs = -1,random_state=42)
scores = cross_validate(rf,train_input,train_target,return_train_score=True,n_jobs = -1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

0.9973541965122431 0.8905151032797809


In [3]:
rf.fit(train_input,train_target)
print(rf.feature_importances_) # 특성 중요도

[0.23167441 0.50039841 0.26792718]


In [4]:
# OOB(Out of Bag): 훈련 세트 샘플 중 부트스트랩 샘플에 포함되지 않은 남은 샘플
# oob_score_: 랜덤 포레스트 내 각 결정 트리의 OOB 점수의 평균
rf = RandomForestClassifier(oob_score = True,n_jobs = -1,random_state=42)
rf.fit(train_input,train_target)
print(rf.oob_score_)

0.8934000384837406


In [5]:
print(rf.score(train_input,train_target))
print(rf.score(test_input,test_target))

0.996921300750433
0.8892307692307693


In [6]:
# 엑스트라 트리(부트스트랩 사용 X)
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs = -1,random_state=42)
scores = cross_validate(et,train_input,train_target,return_train_score=True,n_jobs = -1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

0.9974503966084433 0.8887848893166506


In [7]:
et.fit(train_input,train_target)
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]


In [8]:
print(et.score(train_input,train_target))
print(et.score(test_input,test_target))

0.996921300750433
0.8861538461538462


In [9]:
# 그리디언트 트리 부스팅
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb,train_input,train_target,return_train_score=True,n_jobs = -1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

0.8881086892152563 0.8720430147331015


In [10]:
gb = GradientBoostingClassifier(n_estimators = 500,learning_rate = 0.2,random_state=42)
scores = cross_validate(gb,train_input,train_target,return_train_score=True,n_jobs = -1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

0.9464595437171814 0.8780082549788999


In [11]:
gb.fit(train_input,train_target)
print(gb.feature_importances_)

[0.15872278 0.68010884 0.16116839]


In [12]:
print(gb.score(train_input,train_target))
print(gb.score(test_input,test_target))

0.9382335963055609
0.8707692307692307
